
name: Build Windows Portable EXE

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build (electron-builder)
        run: npm run dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fake-ie-windows
          path: dist/*.exe
